;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Enemy.Event.Teleport.Complete",DevComment="")
+GameplayTagList=(Tag="Frontend.Widget.CreditScreen",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Buff.DefenseUp",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Buff.PowerUp",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Death.AxeGuy",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Death.FistBro",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Death.Killer",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Death.SwordBro",DevComment="")
+GameplayTagList=(Tag="GameplayCue.FX.Ability.Light.AOE",DevComment="")
+GameplayTagList=(Tag="GameplayCue.FX.Bomb.Execute",DevComment="")
+GameplayTagList=(Tag="GameplayCue.FX.Bomb.PerfectDodge",DevComment="")
+GameplayTagList=(Tag="GameplayCue.FX.Bomb.Sprint",DevComment="")
+GameplayTagList=(Tag="GameplayCue.FX.Bomb.SprintShadow",DevComment="GA Sprint Shadow 專用的gameplay cue")
+GameplayTagList=(Tag="GameplayCue.FX.Bomb.VoidDevour",DevComment="")
+GameplayTagList=(Tag="GameplayCue.FX.Katana.Block.PerfectBlock",DevComment="")
+GameplayTagList=(Tag="GameplayCue.FX.Katana.Block.SuccessBlock",DevComment="")
+GameplayTagList=(Tag="GameplayCue.FX.PerfectDodge",DevComment="")
+GameplayTagList=(Tag="GameplayCue.FX.Stunned",DevComment="")
+GameplayTagList=(Tag="GameplayCue.FX.Transcendence.Activating",DevComment="")
+GameplayTagList=(Tag="GameplayCue.FX.UnblockableWarning",DevComment="")
+GameplayTagList=(Tag="GameplayCue.HitEffect.Katana",DevComment="")
+GameplayTagList=(Tag="GameplayCue.HitEffect.Sai",DevComment="")
+GameplayTagList=(Tag="GameplayCue.VoidTime",DevComment="")
+GameplayTagList=(Tag="Player.Event.OverlayPushed",DevComment="")
+GameplayTagList=(Tag="Shared.SetByCaller.HealAmount",DevComment="")
+GameplayTagList=(Tag="Tests.Event",DevComment="")

